-- Tables
CREATE TABLE USUARIO (
  ID INTEGER PRIMARY KEY,
  NOME TEXT NOT NULL,
  SENHA TEXT NOT NULL,
  EMAIL TEXT NOT NULL
);

CREATE TABLE CATEGORIA (
  ID INTEGER PRIMARY KEY,
  NOME TEXT NOT NULL
);

INSERT INTO CATEGORIA VALUES (0001, 'Audio');
INSERT INTO CATEGORIA VALUES (0002, 'Audiovisual');

CREATE TABLE MIDIA (
  ID INTEGER PRIMARY KEY,
  CATEGORIA_ID INTEGER NOT NULL,
  NOME TEXT NOT NULL,
  SINOPSE TEXT NOT NULL,
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE COMENTARIO (
  ID INTEGER PRIMARY KEY,
  USUARIO_ID INTEGER NOT NULL,
  MIDIA_ID INTEGER NOT NULL,
  DATA DATE NOT NULL,
  TEXTO TEXT NOT NULL,
  NOTA INTEGER NOT NULL,
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
  FOREIGN KEY (MIDIA_ID) REFERENCES MIDIA(ID)
);

CREATE TABLE MIDIA_FAVORITADA (
  MIDIA_ID INTEGER NOT NULL,
  USUARIO_ID INTEGER NOT NULL,
  DATA DATE NOT NULL,
  FOREIGN KEY (MIDIA_ID) REFERENCES MIDIA(ID),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE TAG (
  ID INTEGER PRIMARY KEY,
  NOME TEXT NOT NULL
);

CREATE TABLE MIDIA_TAG (
  MIDIA_ID INTEGER NOT NULL,
  TAG_ID INTEGER NOT NULL,
  DATA_ASSOCIACAO DATE NOT NULL,
  PESO INTEGER NOT NULL,
  FOREIGN KEY (MIDIA_ID) REFERENCES MIDIA(ID),
  FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

-- fetch 
SELECT * FROM CATEGORIA;
